jdk:
- openjdk8
dist: trusty
language: android
android:
  components:
  - android-29
  - build-tools-29.0.3
script:
- git clone --depth=1 --branch=master https://github.com/Anuken/Arc
- git clone --depth=1 --branch=master-ci https://github.com/ILiekMelons/Mindustry
- cd Mindustry
- echo "sdk.dir=/usr/local/android-sdk" > local.properties
- sed -i 's/applicationId "io.anuke.mindustry"/applicationId "io.anuke.mindustry.be"/g' android/build.gradle
- sed -i 's/"io.anuke.mindustry"/"io.ILiekMelons.mindustry"/g' android/AndroidManifest.xml
- sed -i 's/Mindustry/Not Mindustry BE/g' android/res/values/strings.xml
- "./gradlew android:assembleDebug -Pbuildversion=${TRAVIS_TAG} -PversionType=bleeding-edge"
- mv android/build/outputs/apk/debug/android-debug.apk android/build/outputs/apk/debug/Mindustry-BE-Android-${TRAVIS_TAG}.apk
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API
  draft: false
  file:
  - android/build/outputs/apk/debug/Mindustry-BE-Android-${TRAVIS_TAG}.apk
  on:
    repo: ILiekMelons/MindustryBuilds
    tags: true
